import type { Lesson, Sign, UserProgress, Badge } from "./types"

export const mockSigns: Sign[] = [
  {
    id: "1",
    word: "Hello",
    category: "greetings",
    videoUrl: "/jsl-hello-sign.jpg",
    thumbnailUrl: "/jsl-hello-sign.jpg",
    description: "A friendly greeting gesture",
    difficulty: "beginner",
  },
  {
    id: "2",
    word: "Thank You",
    category: "greetings",
    videoUrl: "/jsl-thank-you-sign.jpg",
    thumbnailUrl: "/jsl-thank-you-sign.jpg",
    description: "Express gratitude",
    difficulty: "beginner",
  },
  {
    id: "3",
    word: "Please",
    category: "greetings",
    videoUrl: "/jsl-please-sign.jpg",
    thumbnailUrl: "/jsl-please-sign.jpg",
    description: "Polite request gesture",
    difficulty: "beginner",
  },
]

export const mockLessons: Lesson[] = [
  {
    id: "1",
    title: "Basic Greetings",
    description: "Learn essential greeting signs to start conversations",
    category: "basics",
    difficulty: "beginner",
    duration: 15,
    signs: mockSigns,
    completed: false,
    locked: false,
    xpReward: 100,
  },
  {
    id: "2",
    title: "JSL Alphabet",
    description: "Master the Jamaican Sign Language alphabet",
    category: "alphabet",
    difficulty: "beginner",
    duration: 20,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 150,
  },
  {
    id: "3",
    title: "Numbers 1-20",
    description: "Learn to sign numbers from 1 to 20",
    category: "numbers",
    difficulty: "beginner",
    duration: 15,
    signs: [],
    completed: false,
    locked: true,
    xpReward: 120,
  },
  {
    id: "4",
    title: "Common Phrases",
    description: "Everyday phrases for basic communication",
    category: "phrases",
    difficulty: "intermediate",
    duration: 25,
    signs: [],
    completed: false,
    locked: true,
    xpReward: 200,
  },
]

export const mockBadges: Badge[] = [
  {
    id: "1",
    name: "First Steps",
    description: "Complete your first lesson",
    icon: "🎯",
    unlockedAt: "",
    rarity: "common",
  },
  {
    id: "2",
    name: "Week Warrior",
    description: "Maintain a 7-day streak",
    icon: "🔥",
    unlockedAt: "",
    rarity: "rare",
  },
  {
    id: "3",
    name: "Perfect Score",
    description: "Get 100% on a quiz",
    icon: "⭐",
    unlockedAt: "",
    rarity: "epic",
  },
  {
    id: "4",
    name: "Sign Master",
    description: "Learn 100 signs",
    icon: "👑",
    unlockedAt: "",
    rarity: "legendary",
  },
]

export const mockUserProgress: UserProgress = {
  userId: "1",
  level: 3,
  xp: 450,
  xpToNextLevel: 550,
  streak: 5,
  lastActiveDate: new Date().toISOString(),
  completedLessons: [],
  badges: [],
  stats: {
    totalSignsLearned: 12,
    totalPracticeTime: 120,
    quizzesPassed: 2,
    perfectScores: 1,
  },
}
