import type { Lesson, LessonContent } from "./types"

// Hardcoded modules data
export const modulesData = {
  1: {
    id: 1,
    name: "JSL Basics",
    description: "Learn the fundamentals of Jamaican Sign Language",
    difficulty: "Beginner",
  },
  2: {
    id: 2,
    name: "Alphabet & Numbers",
    description: "Master the JSL alphabet and number signs",
    difficulty: "Beginner",
  },
  3: {
    id: 3,
    name: "Common Phrases",
    description: "Everyday phrases for basic communication",
    difficulty: "Intermediate",
  },
  4: {
    id: 4,
    name: "Emotions & Expressions",
    description: "Learn to express feelings and emotions",
    difficulty: "Intermediate",
  },
  5: {
    id: 5,
    name: "Commands & Directions",
    description: "Essential commands and directional signs",
    difficulty: "Intermediate",
  },
  6: {
    id: 6,
    name: "Advanced Conversations",
    description: "Complex conversations and storytelling",
    difficulty: "Advanced",
  },
}

// Hardcoded lessons data
export const lessonsData: Lesson[] = [
  // Module 1: JSL Basics
  {
    id: "1-1",
    name: "Basic Greetings",
    description: "Learn essential greeting signs to start conversations",
    moduleId: 1,
    order: 1,
    category: "basics",
    difficulty: "beginner",
    duration: 15,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 100,
    content: [
      {
        id: "1-1-1",
        type: "instruction",
        title: "Hello",
        description: "To sign 'Hello' in JSL, raise your hand to your forehead with fingers together, then move it forward in a small wave motion.",
        videoUrl: "/jsl-hello-sign.jpg",
        tip: "Keep your movements smooth and natural. Smile while signing!",
      },
      {
        id: "1-1-2",
        type: "instruction",
        title: "Thank You",
        description: "Sign 'Thank You' by bringing your open hand from your chin downward and outward in a smooth motion.",
        videoUrl: "/jsl-thank-you-sign.jpg",
        tip: "This gesture shows gratitude and appreciation",
      },
      {
        id: "1-1-3",
        type: "quiz",
        title: "Quick Check",
        description: "Which sign did we learn for expressing gratitude?",
        options: ["Hello", "Thank You", "Please", "Goodbye"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "1-2",
    name: "Polite Expressions",
    description: "Learn polite signs for respectful communication",
    moduleId: 1,
    order: 2,
    category: "basics",
    difficulty: "beginner",
    duration: 12,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 100,
    content: [
      {
        id: "1-2-1",
        type: "instruction",
        title: "Please",
        description: "Make a circular motion on your chest with your open hand to sign 'Please'.",
        videoUrl: "/jsl-please-sign.jpg",
        tip: "Use a gentle, respectful tone with your facial expression",
      },
      {
        id: "1-2-2",
        type: "instruction",
        title: "Excuse Me",
        description: "Gently tap your chest with your fingertips to sign 'Excuse Me'.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "This is used to get someone's attention politely",
      },
      {
        id: "1-2-3",
        type: "quiz",
        title: "Quick Check",
        description: "Which sign is used to get someone's attention politely?",
        options: ["Please", "Excuse Me", "Hello", "Thank You"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "1-3",
    name: "Goodbyes",
    description: "Learn how to say goodbye in JSL",
    moduleId: 1,
    order: 3,
    category: "basics",
    difficulty: "beginner",
    duration: 10,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 100,
    content: [
      {
        id: "1-3-1",
        type: "instruction",
        title: "Goodbye",
        description: "Hold your hand up with palm facing out, then close your fingers down toward your palm in a waving motion.",
        videoUrl: "/person-signing-goodbye-in-sign-language.jpg",
        tip: "This is similar to a regular wave goodbye, but more deliberate",
      },
      {
        id: "1-3-2",
        type: "instruction",
        title: "See You Later",
        description: "Point to your eye, then point forward with both hands in a sweeping motion.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "This sign conveys a casual, friendly goodbye",
      },
      {
        id: "1-3-3",
        type: "quiz",
        title: "Quick Check",
        description: "What does the waving motion with palm out mean?",
        options: ["Hello", "Thank You", "Goodbye", "Please"],
        correctAnswer: 2,
      },
    ],
  },

  // Module 2: Alphabet & Numbers
  {
    id: "2-1",
    name: "Alphabet Basics",
    description: "Learn the JSL alphabet from A to M",
    moduleId: 2,
    order: 1,
    category: "alphabet",
    difficulty: "beginner",
    duration: 20,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 150,
    content: [
      {
        id: "2-1-1",
        type: "instruction",
        title: "Letters A-E",
        description: "Learn the hand shapes for the first five letters of the alphabet.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Keep your hand steady and clear for each letter",
      },
      {
        id: "2-1-2",
        type: "instruction",
        title: "Letters F-J",
        description: "Continue with the next set of alphabet letters.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Practice each letter slowly before moving to the next",
      },
      {
        id: "2-1-3",
        type: "quiz",
        title: "Quick Check",
        description: "Which hand shape represents the letter 'A'?",
        options: ["Closed fist", "Open hand", "Curved hand", "Spread fingers"],
        correctAnswer: 0,
      },
    ],
  },
  {
    id: "2-2",
    name: "Numbers 1-10",
    description: "Learn to sign numbers from 1 to 10",
    moduleId: 2,
    order: 2,
    category: "alphabet",
    difficulty: "beginner",
    duration: 15,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 150,
    content: [
      {
        id: "2-2-1",
        type: "instruction",
        title: "Numbers 1-5",
        description: "Learn how to sign numbers one through five using your fingers.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Hold your hand steady with palm facing outward",
      },
      {
        id: "2-2-2",
        type: "instruction",
        title: "Numbers 6-10",
        description: "Continue with numbers six through ten.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "For 6-10, use both hands or specific hand positions",
      },
      {
        id: "2-2-3",
        type: "quiz",
        title: "Quick Check",
        description: "How do you sign the number '5'?",
        options: ["Closed fist", "All fingers spread", "Three fingers up", "Two fingers up"],
        correctAnswer: 1,
      },
    ],
  },

  // Module 3: Common Phrases
  {
    id: "3-1",
    name: "Greetings & Questions",
    description: "Learn how to greet and ask basic questions",
    moduleId: 3,
    order: 1,
    category: "phrases",
    difficulty: "intermediate",
    duration: 18,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 200,
    content: [
      {
        id: "3-1-1",
        type: "instruction",
        title: "How are you?",
        description: "'How are you?' requires proper hand movements and facial expressions.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Use a questioning facial expression when signing this",
      },
      {
        id: "3-1-2",
        type: "instruction",
        title: "What is your name?",
        description: "When asking for a name, use proper hand shape and make eye contact.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Point to the person and use a questioning expression",
      },
      {
        id: "3-1-3",
        type: "quiz",
        title: "Quick Check",
        description: "Which sign did we learn for asking someone's name?",
        options: ["How are you?", "What is your name?", "Nice to meet you", "Where are you from?"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "3-2",
    name: "Introductions",
    description: "Learn how to introduce yourself and others",
    moduleId: 3,
    order: 2,
    category: "phrases",
    difficulty: "intermediate",
    duration: 16,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 200,
    content: [
      {
        id: "3-2-1",
        type: "instruction",
        title: "Nice to meet you",
        description: "'Nice to meet you' combines greeting and appreciation gestures.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Show genuine warmth in your facial expression",
      },
      {
        id: "3-2-2",
        type: "instruction",
        title: "Where are you from?",
        description: "This phrase uses specific hand positions and movements.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Use directional movements to indicate location",
      },
      {
        id: "3-2-3",
        type: "quiz",
        title: "Quick Check",
        description: "Which phrase combines greeting and appreciation gestures?",
        options: ["How are you?", "Nice to meet you", "Where are you from?", "What is your name?"],
        correctAnswer: 1,
      },
    ],
  },

  // Module 4: Emotions & Expressions
  {
    id: "4-1",
    name: "Basic Emotions",
    description: "Learn to express basic emotions in JSL",
    moduleId: 4,
    order: 1,
    category: "emotions",
    difficulty: "intermediate",
    duration: 17,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 200,
    content: [
      {
        id: "4-1-1",
        type: "instruction",
        title: "Happy",
        description: "'I'm happy' is shown with a smile and upward hand movements.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Your facial expression is crucial for this sign",
      },
      {
        id: "4-1-2",
        type: "instruction",
        title: "Sad",
        description: "'I'm sad' is shown with a frown and downward hand movements.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Use a sad facial expression to accompany the sign",
      },
      {
        id: "4-1-3",
        type: "quiz",
        title: "Quick Check",
        description: "Which sign is shown with upward hand movements and a smile?",
        options: ["I'm sad", "I'm happy", "I'm tired", "I'm confused"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "4-2",
    name: "More Emotions",
    description: "Learn additional emotional expressions",
    moduleId: 4,
    order: 2,
    category: "emotions",
    difficulty: "intermediate",
    duration: 15,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 200,
    content: [
      {
        id: "4-2-1",
        type: "instruction",
        title: "Tired",
        description: "'I'm tired' is shown with hands moving downward near the face.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Show exhaustion in your facial expression",
      },
      {
        id: "4-2-2",
        type: "instruction",
        title: "Excited",
        description: "Show excitement with energetic hand movements and a bright expression.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Use enthusiastic facial expressions and quick movements",
      },
      {
        id: "4-2-3",
        type: "quiz",
        title: "Quick Check",
        description: "How do you show that you're tired?",
        options: ["Upward movements", "Downward movements near face", "Quick movements", "Circular movements"],
        correctAnswer: 1,
      },
    ],
  },

  // Module 5: Commands & Directions
  {
    id: "5-1",
    name: "Essential Commands",
    description: "Learn important command signs",
    moduleId: 5,
    order: 1,
    category: "commands",
    difficulty: "intermediate",
    duration: 16,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 250,
    content: [
      {
        id: "5-1-1",
        type: "instruction",
        title: "Stop",
        description: "'Stop' is signed with an open hand held up in front of you.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Make the sign firm and clear",
      },
      {
        id: "5-1-2",
        type: "instruction",
        title: "Go",
        description: "'Go' is signed by moving your hand forward with fingers pointing ahead.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Use a forward, directional motion",
      },
      {
        id: "5-1-3",
        type: "quiz",
        title: "Quick Check",
        description: "Which sign is made with an open hand held up in front?",
        options: ["Go", "Stop", "Wait", "Come"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "5-2",
    name: "Directions & Movement",
    description: "Learn directional and movement signs",
    moduleId: 5,
    order: 2,
    category: "commands",
    difficulty: "intermediate",
    duration: 14,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 250,
    content: [
      {
        id: "5-2-1",
        type: "instruction",
        title: "Wait",
        description: "'Wait' is signed with both hands held up with palms facing forward.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Keep your hands steady and visible",
      },
      {
        id: "5-2-2",
        type: "instruction",
        title: "Come",
        description: "'Come' is signed by curling your fingers inward in a beckoning motion.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Use a welcoming, inviting motion",
      },
      {
        id: "5-2-3",
        type: "quiz",
        title: "Quick Check",
        description: "How do you sign 'Come'?",
        options: ["Open hand up", "Beckoning motion", "Forward motion", "Downward motion"],
        correctAnswer: 1,
      },
    ],
  },

  // Module 6: Advanced Conversations
  {
    id: "6-1",
    name: "Understanding & Agreement",
    description: "Learn signs for understanding and expressing agreement",
    moduleId: 6,
    order: 1,
    category: "advanced",
    difficulty: "advanced",
    duration: 20,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 300,
    content: [
      {
        id: "6-1-1",
        type: "instruction",
        title: "I understand",
        description: "'I understand' is signed by tapping your forehead with your index finger.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Use a confident expression",
      },
      {
        id: "6-1-2",
        type: "instruction",
        title: "I agree",
        description: "'I agree' is signed with a nodding motion and thumbs up.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Combine the sign with a positive facial expression",
      },
      {
        id: "6-1-3",
        type: "quiz",
        title: "Quick Check",
        description: "Which sign is made by tapping your forehead?",
        options: ["I'm confused", "I understand", "I agree", "I disagree"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "6-2",
    name: "Disagreement & Confusion",
    description: "Learn how to express disagreement and confusion",
    moduleId: 6,
    order: 2,
    category: "advanced",
    difficulty: "advanced",
    duration: 18,
    signs: [],
    completed: false,
    locked: false,
    xpReward: 300,
    content: [
      {
        id: "6-2-1",
        type: "instruction",
        title: "I'm confused",
        description: "'I'm confused' is signed by moving your hand in a circular motion near your head.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Show confusion in your facial expression",
      },
      {
        id: "6-2-2",
        type: "instruction",
        title: "I disagree",
        description: "'I disagree' is signed with a head shake and thumbs down.",
        videoUrl: "/abstract-hand-gesture-pattern.jpg",
        tip: "Use a respectful but firm expression",
      },
      {
        id: "6-2-3",
        type: "quiz",
        title: "Quick Check",
        description: "How do you express disagreement?",
        options: ["Thumbs up and nodding", "Thumbs down and head shake", "Circular motion", "Tapping forehead"],
        correctAnswer: 1,
      },
    ],
  },
]

export const getLessonsByModule = (moduleId: number): Lesson[] => {
  return lessonsData.filter(lesson => lesson.moduleId === moduleId)
}

export const getLessonById = (lessonId: string): Lesson | undefined => {
  return lessonsData.find(lesson => lesson.id === lessonId)
}
